apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ include "mungcle.namespace" . }}
  labels:
    {{- include "mungcle.labels" . | nindent 4 }}
    {{- include "mungcle.selectorLabels" (dict "component" "api-gateway") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mungcle.selectorLabels" (dict "component" "api-gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.apiGateway.port }}
      targetPort: http
