apiVersion: v1
kind: ConfigMap
metadata:
  name: mungcle-config
  namespace: {{ include "mungcle.namespace" . }}
  labels:
    {{- include "mungcle.labels" . | nindent 4 }}
data:
  DB_HOST: postgres
  DB_PORT: "{{ .Values.postgres.port }}"
  DB_NAME: {{ .Values.postgres.database }}
  DB_USERNAME: {{ .Values.postgres.username }}
  KAFKA_BOOTSTRAP: "kafka:{{ .Values.kafka.port }}"
  OTEL_HOST: otel-collector
  IDENTITY_HOST: identity
  PET_PROFILE_HOST: pet-profile
  WALKS_HOST: walks
  SOCIAL_HOST: social
  NOTIFICATION_HOST: notification
