apiVersion: v1
kind: Secret
metadata:
  name: mungcle-secret
  namespace: {{ include "mungcle.namespace" . }}
  labels:
    {{- include "mungcle.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
