apiVersion: v1
kind: Service
metadata:
  name: walks
  namespace: {{ include "mungcle.namespace" . }}
  labels:
    {{- include "mungcle.labels" . | nindent 4 }}
    {{- include "mungcle.selectorLabels" (dict "component" "walks") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mungcle.selectorLabels" (dict "component" "walks") | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.services.walks.port }}
      targetPort: grpc
